# Generated by Django 5.2.15 on 2026-06-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('image', models.ImageField(upload_to='category', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Категорий',
            },
        ),
    ]
